services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    container_name: livreria-container
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - backend

  postgres-db:
    image: postgres:16.0
    container_name: pg-container
    restart: always
    healthcheck:
      test: "exit 0"
    environment:
      - POSTGRES_HOST=pg-container
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=livreria
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./sql/populate.sql:/docker-entrypoint-initdb.d/populate.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge