version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    container_name: livreria-container
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - postgres-db
    networks:
      - backend

  postgres-db:
    image: postgres:16.0
    container_name: pg-container
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=livreria
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge